import globals from "globals";

export default [
  {
    ignores: ["public/lib/**", ".kilo/**", "node_modules/**", ".vercel/**", "dist/**"]
  },
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        ...globals.browser,
        ...globals.node,
        ...globals.jest,
        Deno: "readonly",
        // Window globals
        allStudents: "writable",
        allPayments: "writable",
        allCoaches: "writable",
        allReceipts: "writable",
        allAttendance: "writable",
        currentStudent: "writable",
        accessUsers: "writable",
        securityAlerts: "writable",
        achievementsData: "writable",
        eventsData: "writable",
        allMessages: "writable",
        allRatingHistory: "writable",
        allResources: "writable",
        allBatches: "writable",
        allHomework: "writable",
        SUPABASE_URL: "writable",
        SUPABASE_ANON_KEY: "writable",
        API_BASE: "writable",
        // External Libraries
        APP_CONFIG: "readonly",
        XLSX: "readonly",
        // Functions from scripts.js and modules
        getStudentMonthlyFee: "readonly",
        getStudentName: "readonly",
        getStudentRating: "readonly",
        getStudentLevel: "readonly",
        getStudentDate: "readonly",
        getStudentStatus: "readonly",
        getCoachName: "readonly",
        toast: "readonly",
        openModal: "readonly",
        closeModals: "readonly",
        jsAttrEncode: "readonly",
        escapeHtml: "readonly",
        loadAllData: "readonly",
        Chart: "readonly",
        renderChildBilling: "readonly",
        apiCall: "readonly",
        getStudentDueConfig: "readonly",
        downloadReceipt: "readonly",
        downloadFinancialStatement: "readonly",
        shouldShowNotification: "readonly",
        logAudit: "readonly",
        initRealtimeNotifications: "readonly",
        userRole: "readonly",
        fetchLocal: "readonly",
        openEventManagement: "readonly",
        checkCustomCategory: "readonly",
        setExpMonth: "readonly",
        setExpPage: "readonly",
        sendChat: "readonly",
        sendLoginChat: "readonly",
        toggleChat: "readonly",
        toggleLoginChat: "readonly",
        setPage: "readonly",
        doLogin: "readonly",
        doLogout: "readonly",
        finishLogin: "readonly",
        generateAvatarURL: "readonly",
        generateContextualInsight: "readonly",
        renderAttendanceList: "readonly",
        updateAttStats: "readonly",
        informCoachFees: "readonly",
        resetStudMonth: "readonly",
        selectCountryEdit: "readonly",
        selectCountryCoach: "readonly",
        viewPaymentHistory: "readonly",
        informAllDueStudents: "readonly",
        markAllPresent: "readonly",
        markAllAbsent: "readonly",
        toggleMoreMenu: "readonly",
        executeDelete: "readonly",
        setBillTab: "readonly",
        markCoachPaid: "readonly",
        markCoachUnpaid: "readonly",
        informAllCoaches: "readonly",
        CK: "writable",
        Auth: "writable",
        Chess: "readonly",
        html2canvas: "readonly",
        VanillaVirtualizer: "readonly",
        supabase: "readonly",
        Response: "readonly",
        Request: "readonly",
        Headers: "readonly",
        FormData: "readonly",
        Blob: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        TextEncoder: "readonly",
        TextDecoder: "readonly",
        btoa: "readonly",
        atob: "readonly",
        ResizeObserver: "readonly"
      }
    },
    rules: {
      "no-unused-vars": "off",
      "no-undef": "error",
      "no-constant-condition": "warn"
    }
  }
];