import js from "@eslint/js";

export default [
  js.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        "allStudents": "writable",
        "allPayments": "writable",
        "allCoaches": "writable",
        "allReceipts": "writable",
        "currentStudent": "writable",
        "window": "writable",
        "document": "readonly",
        "$": "readonly",
        "getStudentMonthlyFee": "readonly",
        "getStudentName": "readonly",
        "getStudentRating": "readonly",
        "getStudentLevel": "readonly",
        "getStudentDate": "readonly",
        "getStudentStatus": "readonly",
        "toast": "readonly",
        "openModal": "readonly",
        "closeModals": "readonly",
        "jsAttrEncode": "readonly",
        "escapeHtml": "readonly",
        "loadAllData": "readonly",
        "Chart": "readonly",
        "renderChildBilling": "readonly",
        "apiCall": "readonly",
        "API_BASE": "readonly",
        "getStudentDueConfig": "readonly",
        "downloadReceipt": "readonly",
        "downloadFinancialStatement": "readonly",
        "shouldShowNotification": "readonly",
        "logAudit": "readonly",
        "initRealtimeNotifications": "readonly",
        "userRole": "readonly",
        "fetchLocal": "readonly",
        "console": "readonly",
        "setTimeout": "readonly",
        "clearTimeout": "readonly",
        "setInterval": "readonly",
        "clearInterval": "readonly",
        "fetch": "readonly",
        "localStorage": "readonly",
        "sessionStorage": "readonly",
        "Math": "readonly",
        "Date": "readonly",
        "parseFloat": "readonly",
        "parseInt": "readonly",
        "String": "readonly",
        "JSON": "readonly",
        "confirm": "readonly",
        "crypto": "readonly",
        "FileReader": "readonly",
        "Blob": "readonly",
        "URL": "readonly",
        "event": "readonly",
        "supabase": "readonly",
        "XLSX": "readonly",
        "isNaN": "readonly",
        "navigator": "readonly",
        "APP_CONFIG": "readonly",
        "renderAttendanceList": "readonly",
        "updateAttStats": "readonly",
        "informCoachFees": "readonly",
        "generateAvatarURL": "readonly",
        "resetStudMonth": "readonly",
        "selectCountryEdit": "readonly",
        "selectCountryCoach": "readonly",
        "viewPaymentHistory": "readonly",
        "doLogout": "readonly",
        "informAllDueStudents": "readonly",
        "markAllPresent": "readonly",
        "markAllAbsent": "readonly",
        "toggleMoreMenu": "readonly",
        "executeDelete": "readonly",
        "setBillTab": "readonly",
        "markCoachPaid": "readonly",
        "markCoachUnpaid": "readonly"
      }
    },
    rules: {
      "no-unused-vars": "warn",
      "no-undef": "error",
      "no-useless-assignment": "off",
      "no-empty": "off"
    }
  }
];
